# 1.create a 3x3x3 array with random values

In [15]:
import numpy as np

# Create a 3x3x3 array with random values between 0 and 1
random_array = np.random.rand(3, 3, 3)

print(random_array)


[[[0.85689929 0.85808088 0.00337572]
  [0.48923547 0.63882506 0.96427252]
  [0.3867657  0.40397985 0.66653074]]

 [[0.66658034 0.03866485 0.84670099]
  [0.41779362 0.980793   0.81987913]
  [0.17624479 0.41930181 0.26522383]]

 [[0.13439508 0.18407775 0.08309184]
  [0.24048826 0.97511493 0.10494546]
  [0.26026026 0.68844906 0.00132112]]]


# 2.create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [16]:
import numpy as np

# Create a 5x5 matrix filled with zeros
matrix = np.zeros((5, 5))

# Set values 1, 2, 3, 4 just below the diagonal
values = [1, 2, 3, 4]
for i in range(1, 5):
    matrix[i, i - 1] = values[i - 1]

print(matrix)


[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


# 3.create a 8x8 matrix and fill it with a checker board pattern

In [17]:
import numpy as np

# Create an 8x8 matrix filled with zeros
matrix = np.zeros((8, 8))

# Use slicing to set alternate rows and columns to 1
matrix[1::2, ::2] = 1
matrix[::2, 1::2] = 1

print(matrix)


[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


# 4.Normalize a 5x5  random matrix

In [18]:
import numpy as np

# Create a 5x5 random matrix
random_matrix = np.random.rand(5, 5)

# Calculate mean and standard deviation
mean = np.mean(random_matrix)
std_dev = np.std(random_matrix)

# Normalize the matrix
normalized_matrix = (random_matrix - mean) / std_dev

print("Original Random Matrix:")
print(random_matrix)
print("\nNormalized Matrix:")
print(normalized_matrix)


Original Random Matrix:
[[0.30210123 0.29903621 0.22180324 0.47163304 0.67199503]
 [0.99322081 0.56099575 0.44455213 0.51857298 0.92089646]
 [0.69033668 0.87157587 0.39384422 0.33817285 0.24231791]
 [0.81096526 0.35211497 0.09969493 0.57819324 0.81316178]
 [0.92603898 0.58679768 0.89945934 0.78029412 0.54685879]]

Normalized Matrix:
[[-1.08227289 -1.09450063 -1.40261728 -0.40593516  0.39339789]
 [ 1.6749103  -0.04942758 -0.51397294 -0.21867086  1.38637633]
 [ 0.46657087  1.18961455 -0.71626934 -0.93836718 -1.32077513]
 [ 0.94781189 -0.88274586 -1.88976159  0.01918086  0.95657481]
 [ 1.40689211  0.05350779  1.30085412  0.82545109 -0.10582618]]


# 5. How to find common value between two arrays?

In [19]:
import numpy as np

# Create two NumPy arrays
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([3, 4, 5, 6, 7])

# Find common values between the two arrays
common_values = np.intersect1d(array1, array2)

print("Common values:", common_values)

Common values: [3 4 5]


# 6. How to get the dates of yesterday, today, tomorrow?

In [21]:
import numpy as np
from datetime import datetime, timedelta

# Get the current date (today)
today = datetime.now().date()

# Calculate yesterday and tomorrow
yesterday = today - timedelta(days=1)
tomorrow = today + timedelta(days=1)

# Create NumPy arrays for the dates
dates = np.array([yesterday, today, tomorrow])

# Format the dates as strings if needed
date_strings = [date.strftime("%Y-%m-%d") for date in dates]

print("Yesterday:", date_strings[0])
print("Today:", date_strings[1])
print("Tomorrow:", date_strings[2])

Yesterday: 2023-09-20
Today: 2023-09-21
Tomorrow: 2023-09-22


# 7.consider two random array A and B check if they are equal

In [37]:
import numpy as np

# Generate two random arrays A and B
A = np.random.rand(5, 5)
B = np.random.rand(5, 5)

# Check if the arrays are equal
if np.array_equal(A, B):
    print("Arrays A and B are equal.")
else:
    print("Arrays A and B are not equal.")

Arrays A and B are not equal.


# 8.create a random vector of size 10 and replace the maximum value by 0

In [22]:
import numpy as np

# Create a random vector of size 10
random_vector = np.random.rand(10)

# Find the index of the maximum value in the vector
max_index = np.argmax(random_vector)

# Replace the maximum value with 0
random_vector[max_index] = 0

print("Random Vector:")
print(random_vector)


Random Vector:
[0.21840062 0.44774963 0.34138071 0.00304264 0.95406816 0.73904118
 0.95503512 0.         0.26775025 0.13697364]


# 9. How to print all the values of an array?

In [24]:
import numpy as np

# Create a NumPy array
my_array = np.array([1, 2, 3, 4, 5])

# Iterate through the array and print each value
for value in my_array:
    print(value)

1
2
3
4
5


# 10.subtract the mean of each row of a matrix

In [23]:
import numpy as np

# Create a sample matrix (you can replace this with your own matrix)
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Calculate the mean of each row
row_means = np.mean(matrix, axis=1, keepdims=True)

# Subtract the row means from the matrix using broadcasting
normalized_matrix = matrix - row_means

print("Original Matrix:")
print(matrix)
print("\nMatrix with Row Means Subtracted:")
print(normalized_matrix)


Original Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix with Row Means Subtracted:
[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


# 11.consider a given vector how to add 1 to each element indexed by a second vector(be careful with repeated indices)?

In [25]:
import numpy as np

# Given vector
given_vector = np.array([10, 20, 30, 40, 50])

# Second vector with indices
indices_to_add_1 = np.array([1, 2, 3, 3, 4])

# Find unique indices and their counts
unique_indices, counts = np.unique(indices_to_add_1, return_counts=True)

# Add 1 to each element at the unique indices
given_vector[unique_indices] += counts

print("Given Vector:")
print(given_vector)

Given Vector:
[10 21 31 42 51]


# 12. How to get a diagonal of dot product?

In [29]:
import numpy as np

# Create two matrices
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

# Compute the dot product of the two matrices
dot_product = np.dot(matrix1, matrix2)

# Extract the diagonal elements using np.diag
diagonal_elements = np.diag(dot_product)

print("Dot Product:")
print(dot_product)

print("\nDiagonal Elements:")
print(diagonal_elements)

Dot Product:
[[19 22]
 [43 50]]

Diagonal Elements:
[19 50]


# 13.How to find the most frequent value in an array?

In [31]:
import numpy as np

# Create a NumPy array (you can replace this with your own array)
arr = np.array([0,10,50])

# Find the most frequent value
most_frequent_value = np.bincount(arr).argmax()

print("Most frequent value:", most_frequent_value)


Most frequent value: 0


# 14.How to get the n largest values of an array

In [27]:
import numpy as np

# Create a NumPy array (you can replace this with your own array)
arr = np.array([5, 2, 8, 1, 9, 3, 7, 4, 6])

# Get the n largest values (e.g., n=3)
n = 3
n_largest_values = np.partition(arr, -n)[-n:]

print("N largest values:", n_largest_values)


N largest values: [7 8 9]


# 15.How to create a record array from a regular array?

In [28]:
import numpy as np

# Create a regular array
regular_array = np.array([(1, 'Alice', 25),
                          (2, 'Bob', 30),
                          (3, 'Charlie', 22)],
                         dtype=[('ID', int), ('Name', 'U10'), ('Age', int)])

# 'ID', 'Name', and 'Age' are the field names, and their data types are specified.

# Accessing data in the record array
print("ID:", regular_array['ID'])
print("Name:", regular_array['Name'])
print("Age:", regular_array['Age'])


ID: [1 2 3]
Name: ['Alice' 'Bob' 'Charlie']
Age: [25 30 22]


# 16. How to swap two rows of an array?

In [35]:
import numpy as np

# Create a NumPy array
my_array = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

# Swap rows (for example, swapping row 0 and row 1)
my_array[0, :], my_array[1, :] = my_array[1, :], my_array[0, :]

# Print the modified array
print(my_array)

[[4 5 6]
 [4 5 6]
 [7 8 9]]


# 17.write python code to reshape to the next dimension of numpy array?

In [34]:
import numpy as np

# Create the original NumPy array
x = np.array([[23, 34, 121], [23, 22, 67], [686, 434, 123]])

# Reshape to the next dimension (1x9)
reshaped_array = x.reshape(1, -1)

# Print the reshaped array
print(reshaped_array)


[[ 23  34 121  23  22  67 686 434 123]]
